### ISSUE TITLE
Travis CI ?

### ISSUE THREAD

**Issue by NikolasMelui** [SamaraITCommunity/site#101]
Вспомнил, что GitHub дружит с Travis CI и через него можно билды настраивать.
В дополнение к #100 можно рассмотреть трэвис, но лично у меня такого опыта нет, ничего сказать не могу.
Что-то мне подсказывает, что там не сложно ;-)

**Comment by kortov** [comment]
ну сайт у нас вроде собирается через travis, другой вопрос, ишшуй в чем?) Я вот думаю, может в рамках этого ишшуя добавить [markdown linter](https://github.com/markdownlint/markdownlint) [чекер ссылок](https://github.com/gjtorikian/html-proofer) , только для этого нужно будет текущий travis конфиг доработать, т.к эти линтеры на ruby вызываются

**Comment by humb1t** [comment]
Не понял смысла иши
