### ISSUE TITLE
Добавить новость о завершении VolgaHack на главную страницу сайта

### ISSUE THREAD

**Issue by humb1t** [SamaraITCommunity/site#3]
По аналогии с https://sitc.community/1-volgahack/ нужно добавить страницу о завершении хакатона:

- [ ] Название - VolgaHack - как это было

- [ ] Содержание можно взять с https://vk.com/@samara_it_community-volgahack-kak-eto-bylo или написать краткое описание и ссылку на статью

- [ ] в конце должен быть shortcode youtube с видеоотчётом https://youtu.be/stIgPLWjiNE

- [ ] должно нормально отображаться на мобильных\планшетах\пк

- [ ] дата на главной странице должен быть 2018-09-30

- [ ] на главной странице новость должна быть первой

**Comment by privalou** [comment]
начал делать.

**Comment by humb1t** [comment]
Сделана в рамках #7
