### ISSUE TITLE
Задать favicon

### ISSUE THREAD

**Issue by speker2010** [SamaraITCommunity/site#32]
Можно использовать сервис для генерации favicon https://realfavicongenerator.net/

**Comment by humb1t** [comment]
![img_1729](https://user-images.githubusercontent.com/5635032/49344683-43ed0680-f694-11e8-9936-5148eadf7afe.jpg)

**Comment by humb1t** [comment]
[favicon_package_v0.16.zip](https://github.com/SamaraITCommunity/site/files/2637370/favicon_package_v0.16.zip)

**Comment by humb1t** [comment]
`

<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

`
