### ISSUE TITLE
Ошибка zola build - Failed to render pager

### ISSUE THREAD

**Issue by avchirkin** [SamaraITCommunity/site#92]
Шаги воспроизведения:
1. Выкачать репозиторий с master-ветки
2. Проинициализировать и обновить сабмодули репозитория
3. Установить zola с помощью choco
4. Запустить zola build из директории site

Ошибка приведена на скрине:
![image](https://user-images.githubusercontent.com/44869074/61323317-b45e2780-a820-11e9-9709-b15993799026.png)

**Comment by avchirkin** [comment]
Проблема исчезает, если вытащить директории из content в корень репозитория, т.е., в site

**Comment by speker2010** [comment]
У меня нет такого. Тоже choco. Попробовал выкачать в отдельную папку, все собралось
